export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST'
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS'
export const SINGLE_PRODUCT_FAIL = 'SINGLE_PRODUCT_FAIL'

export const ADD_TO_CART='ADD_TO_CART'
export const REMOVE_FROM_CART='REMOVE_FROM_CART'

export const USER_REQUESTING_LOGIN='USER_REQUESTING_LOGIN'
export const USER_LOGIN_SUCESS='USER_LOGIN_SUCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'
export const USER_LOGOUT='USER_LOGOUT'

export const USER_REQUESTING_REGISTER='USER_REQUESTING_REGISTER'
export const USER_REGISTER_SUCESS='USER_REGISTER_SUCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'

export const USER_REQUESTING_PROFILE='USER_REQUESTING_PROFILE'
export const USER_PROFILE_SUCESS='USER_PROFILE_SUCESS'
export const USER_PROFILE_FAIL='USER_PROFILE_FAIL'



